#!/bin/bash
rm ./0-current_working_directory~ ./10-back~ ./12-file_type~ ./14-copy_html~ ./1-listit~ ./2-bring_me_home~ ./3-listfiles~ ./4-listmorefiles~ ./6-firstdirectory~ ./7-movethatfile~ ./8-firstdelete~ ./9-firstdirdeletion~
